#!/bin/bash

# Extracts docs from Yii 2 and main extensions an updates the according files
# in the docs/ directory.
#
# Recipe to upgrade to new Yii version:
#
#  1. Update Yii version in composer.json
#  2. composer update --ignore-platform-reqs
#  3. ./update-all (maybe first remove vendor/yiisoft/yii2/base/Object.php to avoid error)
#  4. Run `:helptags doc` in vim
#  5. Commit

for dir in ./vendor/yiisoft/*/
do
    echo "Extracting docs from $dir"
    ./apidocvim api --interactive=0 $dir ./doc
    echo
done
